apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzb-app
spec:
  replicas: 1
    spec:
      containers:
        - name: sabnzb
          image: linuxserver/sabnzbd:latest
          env:
            - name: SECRET_USERNAME
              value: "your-username-value"
            - name: SECRET_PASSWORD
              value: "your-password-value"
            - name: SECRET_API_KEY
              value: "your-api-key-value"
      volumes:
        # Add volumes if needed
