apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzb-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sabnzb-ui
  template:
    metadata:
      labels:
        app: sabnzb-ui
    spec:
      containers:
      - image: linuxserver/sabnzbd:latest
        name: sabnzb
        ports:
        - containerPort: 8080
